name: A2Content
favicon: null
layout_spectrum: 0
typography_spectrum: 0.86667
title: "Strategic Multi-Media Content Production. #B2B #VIDEO\_#PHOTO\_#WEB #EMPOWERING"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b1b3ac'
    - '#ff7d00'
    - '#d8d9d5'
    - '#ffa54f'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
